# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.0.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-03-29T08:05:06Z"
  labels:
    app: SQLServer2017
  name: SQLServer2017
spec:
  containers:
  - args:
    - /opt/mssql/bin/sqlservr
    command:
    - /opt/mssql/bin/nonroot_msg.sh
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: SA_PASSWORD
      value: Tekapp2021!
    - name: ACCEPT_EULA
      value: "Y"
    image: docker.io/tekappsrl/cent-lab_sqlserver:2017-latest
    name: SQLServer2017
    ports:
    - containerPort: 1433
      hostPort: 10101
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsUser: 0
      seLinuxOptions: {}
    tty: true
    workingDir: /
  dnsConfig: {}
status: {}
